// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcWgN2o1610hKvFmZuLOYmmPf-Xap2j34',
    appId: '1:566388150386:web:1da61abc73574979ed32eb',
    messagingSenderId: '566388150386',
    projectId: 'rakan-10680',
    authDomain: 'rakan-10680.firebaseapp.com',
    storageBucket: 'rakan-10680.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm959cO5eMAfzJNmt9TOcv7BJt9rlBPD4',
    appId: '1:566388150386:android:8dcd71001c4eb198ed32eb',
    messagingSenderId: '566388150386',
    projectId: 'rakan-10680',
    storageBucket: 'rakan-10680.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARELxlFjep3xZz0U_28qNSvRYKz504IPE',
    appId: '1:566388150386:ios:e14f46c9f8cf3d5fed32eb',
    messagingSenderId: '566388150386',
    projectId: 'rakan-10680',
    storageBucket: 'rakan-10680.firebasestorage.app',
    iosClientId: '566388150386-cni7d9vgsqu805cn4jnu7ad0l3bbmo9f.apps.googleusercontent.com',
    iosBundleId: 'com.example.rakan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARELxlFjep3xZz0U_28qNSvRYKz504IPE',
    appId: '1:566388150386:ios:e14f46c9f8cf3d5fed32eb',
    messagingSenderId: '566388150386',
    projectId: 'rakan-10680',
    storageBucket: 'rakan-10680.firebasestorage.app',
    iosClientId: '566388150386-cni7d9vgsqu805cn4jnu7ad0l3bbmo9f.apps.googleusercontent.com',
    iosBundleId: 'com.example.rakan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcWgN2o1610hKvFmZuLOYmmPf-Xap2j34',
    appId: '1:566388150386:web:bcf9961ec57c951ded32eb',
    messagingSenderId: '566388150386',
    projectId: 'rakan-10680',
    authDomain: 'rakan-10680.firebaseapp.com',
    storageBucket: 'rakan-10680.firebasestorage.app',
  );
}
